---
# This will install apache

- name: install apache
  yum: pkg={{ item }} state=present
  with_items:
   - php
   - httpd
   - libsemanage-python
   - libselinux-python
   
- name: http service state
  service: name={{ apache }} state=started enabled=yes

